### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by vmikk** [vmikk/biodiverse-docker#1]
- [x] Fix `Alien::gdal` installation
- [x] Use tagged version of [`biodiverse-utils`](https://github.com/shawnlaffan/biodiverse-utils/)
- [x] Verify that location of Biodiverse scripts is added to the `PATH`

**Comment by vmikk** [comment]
`Alien::gdal` was updated to [r1.27](https://github.com/shawnlaffan/perl-alien-gdal/releases/tag/r1.27)

**Comment by vmikk** [comment]
>Verify that location of Biodiverse scripts is added to the PATH

Environmental variable `PERL5LIB` should be specified, e.g.:
```
export PERL5LIB="/biodiverse/lib"
```
Added in 4b581085.
